### ISSUE TITLE
Where do I download wallet?? Been trying forever now?

### ISSUE THREAD

**Issue by CoinKraken** [storj-archived/storj.io#115]
Hi,
  Can someone give me a good link to where I can download a Storj wallet I've been trying to buy Storj for several months now and all I ever get is a totally blank page. I couldn't buy in at the ICO, I am really becoming frustrated and I can't seem to get it right. Anyone outthere that can direct me to a wallet, or a exchange where I can buy Ethereum or bitcoin then use that to buy Storj tokens? 
It's kill'en me Cuz, kill'en me....... 

Lineberry2@me.com
Thanks,
Gary

**Comment by heunland** [comment]
You can buy STORJ tokens on the exchanges listed on https://coinmarketcap.com/currencies/storj/#markets and then withdraw the tokens to an address from an ERC20 compatible ethereum wallet such as myetherwallet.com, Parity or Mist. To use the exchanges listed above you will first need to get some Bitcoin or Ethereum on an exchange that works in your country. Please google which exchanges are available locally for you. Unless you live in one of the countries that has a fiat gateway for STORJ such as Upbit exchange you need to first get BTC or ETH in order to buy STORJ.
